Repository ono-hikaru81/SuperiorButlers, pull requests merged in 2021-12, with the labels that each got.

#13 ステージ管理クラスの実装 #4
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Manager/StageManager.cpp
  SpesiumBrothers/Src/Manager/StageManager.h
Labels: enhancement

#16 TextureManager
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Manager/TextureManager.cpp
  SpesiumBrothers/Src/Manager/TextureManager.h
Labels: environment

#19 バグ修正 #18
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Manager/Input.cpp
  SpesiumBrothers/Src/Manager/Input.h
  SpesiumBrothers/Src/Manager/StageManager.cpp
  SpesiumBrothers/Src/Manager/StageManager.h
Labels: bug

#21 TextureManger修正
  SpesiumBrothers/Src/Manager/TextureManager.cpp
  SpesiumBrothers/Src/Manager/TextureManager.h
Labels: refactoring

#25 TextureManager再修正
  SpesiumBrothers/Src/Manager/TextureManager.cpp
  SpesiumBrothers/Src/Manager/TextureManager.h
  SpesiumBrothers/Src/WinMain.cpp
Labels: refactoring

#33 人間キャラのクラス追加 - #27
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Character/Human.cpp
  SpesiumBrothers/Src/Character/Human.h
Labels: enhancement

#35 アニメーション管理クラスの追加
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Manager/AnimationManager.cpp
  SpesiumBrothers/Src/Manager/AnimationManager.h
  SpesiumBrothers/Src/WinMain.cpp
Labels: enhancement

#36 SoundManager追加
  SpesiumBrothers/SpesiumBrothers.vcxproj
  SpesiumBrothers/SpesiumBrothers.vcxproj.filters
  SpesiumBrothers/Src/Manager/SoundManager.cpp
  SpesiumBrothers/Src/Manager/SoundManager.h
Labels: enhancement
